// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	updateStatus: (payload: UpdateStatusPayload) => typedError<null, AppError>(__TAURI_INVOKE("update_status", { payload })),
	getById: (payload: GetByIdPayload) => typedError<Game, AppError>(__TAURI_INVOKE("get_by_id", { payload })),
	launchGame: (payload: LaunchGamePayload) => typedError<null, AppError>(__TAURI_INVOKE("launch_game", { payload })),
	syncLibraries: () => typedError<SyncResult, AppError>(__TAURI_INVOKE("sync_libraries")),
};

/* Types */
export type AppError = ({ Database: string }) & { Http?: never; Launch?: never; NotFound?: never; Steam?: never } | ({ NotFound: string }) & { Database?: never; Http?: never; Launch?: never; Steam?: never } | ({ Http: string }) & { Database?: never; Launch?: never; NotFound?: never; Steam?: never } | ({ Steam: string }) & { Database?: never; Http?: never; Launch?: never; NotFound?: never } | ({ Launch: string }) & { Database?: never; Http?: never; NotFound?: never; Steam?: never };

export type Game = {
	id: string,
	name: string,
	game_status_id: number,
	is_favorite: boolean,
	igdb_id: number | null,
};

export type GetByIdPayload = {
	game_id: string,
};

export type LaunchGamePayload = {
	game_launch_id: string,
};

export type SyncResult = {
	games_added: number,
	games_skipped: number,
};

export type UpdateStatusPayload = {
	game_id: string,
	status_id: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

