-- CreateTable
CREATE TABLE "FiltersPreset" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "config" JSONB NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
