import { Emulator } from "@common/constant";

export const dolphin = { id: Emulator.DOLPHIN, name: "Dolphin" };

export const dolphinOptions = [
  {
    emulatorId: Emulator.DOLPHIN,
    name: "version",
    short: null,
    long: "--version",
    description: "show program's version number and exit",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "help",
    short: "-h",
    long: "--help",
    description: "show this help message and exit",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "user",
    short: "-u",
    long: "--user",
    description: "User folder path",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "movie",
    short: "-m",
    long: "--movie",
    description: "Play a movie file",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "exec",
    short: "-e",
    long: "--exec",
    description: "Load the specified file",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "nand_title",
    short: "-n",
    long: "--nand_title",
    description: "Launch a NAND title",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "config",
    short: "-C",
    long: "--config",
    description: "Set a configuration option",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "save_state",
    short: "-s",
    long: "--save_state",
    description: "Load the initial save state",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "debugger",
    short: "-d",
    long: "--debugger",
    description: "Show the debugger pane and additional View menu options",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "logger",
    short: "-l",
    long: "--logger",
    description: "Open the logger",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "batch",
    short: "-b",
    long: "--batch",
    description: "Run Dolphin without the user interface (Requires --exec or --nand-title)",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "confirm",
    short: "-c",
    long: "--confirm",
    description: "Set Confirm on Stop",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "video_backend",
    short: "-v",
    long: "--video_backend",
    description: "Specify a video backend",
    defaultValue: null,
  },
  {
    emulatorId: Emulator.DOLPHIN,
    name: "audio_emulation",
    short: "-a",
    long: "--audio_emulation",
    description: "Choose audio emulation from [HLE|LLE]",
    defaultValue: null,
  },
];
