// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	updateStatus: (payload: UpdateStatusPayload) => typedError<null, AppError>(__TAURI_INVOKE("update_status", { payload })),
	getById: (payload: GetByIdPayload) => typedError<Game, AppError>(__TAURI_INVOKE("get_by_id", { payload })),
};

/* Types */
export type AppError = ({ Database: string }) & { NotFound?: never } | ({ NotFound: string }) & { Database?: never };

export type Game = {
	id: string,
	name: string,
	game_status_id: number,
	is_favorite: boolean,
};

export type GetByIdPayload = {
	game_id: string,
};

export type UpdateStatusPayload = {
	game_id: string,
	status_id: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

